In [1]:
print("Hello, Jupyter!")


Hello, Jupyter!


In [5]:
2+2

4

In [7]:
"hello"

'hello'

#NumPy

## - массивы

In [16]:
import numpy as np

In [18]:
# Установка NumPy
!pip install NumPy

- создание массивов

In [21]:
# создание из списка
my_list = [1,2,3,4]
my_list 

[1, 2, 3, 4]

In [22]:
np.array(my_list)

array([1, 2, 3, 4])

In [23]:
my_array = np.array(my_list)

In [24]:
my_array

array([1, 2, 3, 4])

In [26]:
# создание массива из нулей
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
z.dtype

dtype('float64')

In [28]:
np.zeros(10, dtype="int8")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [29]:
np.zeros(10, dtype="float32")

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [32]:
np.zeros(10, dtype="int64").dtype

dtype('int64')

In [33]:
# 2-мерный массив с формой 2 на 3 (2 строки на 3 столбца)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [35]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
# линейная последовательность
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
np.arange(0,20,2).reshape((2,5))

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [38]:
# вектор, как массив из равномерно распределенных значений
# например, от 0 до 1
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [39]:
# массив размером 3 * 5
# Случайные значения из равномерно распределенного диапазона от 0 до 1
np.random.random(5)

array([0.84404979, 0.62281461, 0.73501581, 0.25498365, 0.42282031])

In [40]:
np.random.random((3, 5))

array([[0.18695155, 0.74425882, 0.84565884, 0.3767552 , 0.61197973],
       [0.32447424, 0.51226621, 0.93188933, 0.22215877, 0.15801352],
       [0.92604526, 0.42575175, 0.69927701, 0.50508932, 0.38795315]])

In [42]:
np.random.random((3, 5)).astype("float16")

array([[0.953  , 0.4412 , 0.3425 , 0.7124 , 0.5776 ],
       [0.17   , 0.608  , 0.819  , 0.08545, 0.947  ],
       [0.3945 , 0.973  , 0.3823 , 0.3755 , 0.7905 ]], dtype=float16)

In [43]:
np.random.random((3, 5)).astype("float32")

array([[0.43030378, 0.04734426, 0.5667974 , 0.25910652, 0.41060615],
       [0.22458562, 0.21976213, 0.43640277, 0.39481905, 0.9575761 ],
       [0.71135783, 0.03558149, 0.24233986, 0.13264394, 0.32138836]],
      dtype=float32)

In [44]:
np.random.random((3, 5)).astype("float")

array([[0.38542333, 0.58359412, 0.52464914, 0.62426532, 0.68222032],
       [0.28904573, 0.15358332, 0.80501635, 0.22436141, 0.11767446],
       [0.45639498, 0.75069057, 0.38179884, 0.68224399, 0.0682266 ]])

In [45]:
# массив с целочисленными случайными значениями
np.random.randint(10)

2

In [46]:
np.random.randint(10,20)

18

In [49]:
np.random.randint(10,size=5)

array([8, 1, 2, 0, 6])

In [50]:
np.random.randint(10,size=(2,3))

array([[2, 5, 5],
       [6, 5, 5]])

In [51]:
np.random.randint(10,20, size=(2,3))

array([[12, 16, 14],
       [15, 15, 16]])

- атрибуты

In [53]:
a1 = np.random.randint(10,20, size=(3,5))
a1

array([[17, 16, 19, 15, 12],
       [15, 17, 11, 12, 14],
       [16, 15, 18, 11, 12]])

In [54]:
# размерность массива(количество измеренийя (осей))
a1.ndim

2

In [55]:
# форма массива
a1.shape

(3, 5)

In [56]:
# размерность массива (количество всех элементов массива)
a1.size

15

In [57]:
# тип значений массива a.1dtype
a1.dtype

dtype('int32')

- индексация

In [58]:
a2 = np.random.randint(20, size=10)
a2
# извлечение элемента по его индексу

array([ 0,  8, 16,  9,  4,  8, 14, 13,  3,  2])

In [59]:
a2[0]

0

In [66]:
a2[-1]

2

In [70]:
a3 = np.random.randint(10, size=(2,3))
a3

array([[3, 3, 9],
       [2, 7, 2]])

In [73]:
a3[0][1]

3

In [74]:
a3[0, 1]

3

срезы

In [61]:
a2[:5]

array([ 0,  8, 16,  9,  4])

In [64]:
a2[1:]


array([ 8, 16,  9,  4,  8, 14, 13,  3,  2])

In [63]:
a2[1:6:2]

array([8, 9, 8])

In [75]:
a3[0, 1:]

array([3, 9])

In [76]:
a3[:, 1:]

array([[3, 9],
       [7, 2]])